version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
          - dependency-cache-{{ checksum "package.json" }}
          - dependency-cache
      - run: npm i
      - run: 
          name: Run Tests
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
        filters:
          tags:
            only: /^[0-9]+(\.[0-9]+)(\.[0-9]+)*$/
          branches: 
            ignore: /.*/
      - deploy:
        requires:
          - build-tag
        filters:
          tags:
            only: /^[0-9]+(\.[0-9]+)(\.[0-9]+)*$/
          branches: 
            ignore: /.*/